FROM arm32v7/python:3.9-alpine

RUN apk add python3-dev gcc musl-dev libffi-dev make
RUN python3 -m ensurepip --default-pip
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt 

COPY bot /

ENTRYPOINT ["python3", "app.py"]
