FROM arm32v7/python:3.9-alpine

COPY bot /

RUN apk add python3-dev gcc musl-dev
RUN python3 -m ensurepip --default-pip
#RUN python3 -m pip install --upgrade pip setuptools wheel
RUN python3 -m pip install discord.py
RUN python3 -m pip install DiscordUtils
RUN python3 -m pip install SQLAlchemy

ENTRYPOINT ["python3", "app.py"]