"""add release_date to Games

Revision ID: 7a219c3ef35c
Revises: 22583dfbe57d
Create Date: 2021-03-02 19:39:15.704572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a219c3ef35c'
down_revision = '22583dfbe57d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Games', sa.Column('release_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Games', 'release_date')
    # ### end Alembic commands ###
