"""Add Servers.banned and Games.is_game columns

Revision ID: 9e96a2e02bec
Revises: 7a219c3ef35c
Create Date: 2022-02-08 19:50:45.394961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e96a2e02bec'
down_revision = '7a219c3ef35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Games', sa.Column('is_game', sa.Boolean(), nullable=True))
    op.add_column('Servers', sa.Column('banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Servers', 'banned')
    op.drop_column('Games', 'is_game')
    # ### end Alembic commands ###
